server:
  port: 9001

spring:
  security:
    oauth2:
      client:
        registration:
          client-oidc:
            client-id: client
            client-secret: secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: openid,read
        provider:
          client-oidc:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9000/userinfo
            user-name-attribute: sub
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false
        domain: localhost  # 쿠키 도메인을 localhost로 설정
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG